### ISSUE TITLE
Error --platform or --push not supported.

### ISSUE THREAD

**Issue by metaskills** [devcontainers/ci#208]
Getting this error when trying to use `platform` added in #175. 

```
2023-02-08T00:38:57.6802644Z ##[group]🏗️ build container
2023-02-08T00:38:57.6811809Z About to run devcontainer build --workspace-folder /home/runner/work/lamby-citest/lamby-citest --image-name ghcr.io/customink/lamby-citest-devcontainer:latest --platform linux/arm64 --output type=oci,dest=/tmp/output.tar --cache-from ghcr.io/customink/lamby-citest-devcontainer:latest --cache-from ghcr.io/customink/lamby-citest-devcontainer
2023-02-08T00:38:57.9391897Z [2023-02-08T00:38:57.937Z] @devcontainers/cli 0.29.0. Node.js v16.19.0. linux 5.15.0-1031-azure x64.
2023-02-08T00:38:57.9392706Z 
2023-02-08T00:38:58.0444615Z Error: --platform or --push not supported.
2023-02-08T00:38:58.0447016Z     at uoe (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2045:27034)
2023-02-08T00:38:58.0449829Z     at async aoe (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2045:25017)
```

```yaml
      - uses: devcontainers/ci@v0.2
        with:
          push: always
          platform: linux/arm64
          imageName: ghcr.io/customink/lamby-citest-devcontainer
          cacheFrom: ghcr.io/customink/lamby-citest-devcontainer
```

## Related Issues or Pull Requests

- https://github.com/devcontainers/ci/pull/175
- https://github.com/devcontainers/cli/issues/106
- https://github.com/devcontainers/ci/issues/151

**Comment by metaskills** [comment]
Closing this issue in favor of one on the CLI. https://github.com/devcontainers/cli/issues/404

**Comment by eduardolat** [comment]
+1
